# Trigger fresh Cloudflare Pages deploy
name = "66hamiltonrd"
compatibility_date = "2026-05-03"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "APPLICATIONS_KV"
id = "c5e3818130844953af3cf9cf5c0b3760"
